apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: costmanagement-metrics-operator
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.24
  name: costmanagement-metrics-operator
